name: magicmirror
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  routemaster: ^1.0.1
  uuid: ^4.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter 

flutter:
  uses-material-design: true
